# coding: utf-8

"""
    Logos Storage API

    List of endpoints and interfaces available to Logos Storage API users

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from codex_api_client.models.has_block200_response import HasBlock200Response

class TestHasBlock200Response(unittest.TestCase):
    """HasBlock200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HasBlock200Response:
        """Test HasBlock200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HasBlock200Response`
        """
        model = HasBlock200Response()
        if include_optional:
            return HasBlock200Response(
                has = True
            )
        else:
            return HasBlock200Response(
        )
        """

    def testHasBlock200Response(self):
        """Test HasBlock200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
