# coding: utf-8

"""
    Logos Storage API

    List of endpoints and interfaces available to Logos Storage API users

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from codex_api_client.models.nat_info import NatInfo

class TestNatInfo(unittest.TestCase):
    """NatInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NatInfo:
        """Test NatInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NatInfo`
        """
        model = NatInfo()
        if include_optional:
            return NatInfo(
                reachability = 'Unknown',
                client_mode = True,
                relay_running = True,
                port_mapping = 'none'
            )
        else:
            return NatInfo(
                reachability = 'Unknown',
                client_mode = True,
                relay_running = True,
                port_mapping = 'none',
        )
        """

    def testNatInfo(self):
        """Test NatInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
